"""added created_by column to users table

Revision ID: 1cacb7f1c051
Revises:
Create Date: 2025-02-14 12:08:58.582985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cacb7f1c051"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("created_by", sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET created_by = 'mounika'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_by")
    # ### end Alembic commands ###
